### PR TITLE
Free image with cl-soil:free-image-data

### PR DESCRIPTION
**Pull request by nja**
This is to play nice with libSOIL.dll on Windows.

See also my cepl and libSOIL.dll repos.

### CODE REVIEW

**Comment by cbaggers** [comment]
Hi, thanks for the work across these repos, however we can just use `#'free-c-array` to do this.

**Comment by nja** [comment]
I'm sorry. I should have provided much better information with the
pull requests. Please bear with me.

This fix is necessary to avoid problems with DLLs and different CRT
copies on Windows.

>   When you pass C Run-time (CRT) objects such as file handles,
>   locales, and environment variables into or out of a DLL (function
>   calls across the DLL boundary), unexpected behavior can occur if the
>   DLL, as well as the files calling into the DLL, use different copies
>   of the CRT libraries.
> 
>   A related problem can occur when you allocate memory (either
>   explicitly with new or malloc, or implicitly with strdup,
>   strstreambuf::str, and so on) and then pass a pointer across a DLL
>   boundary to be freed. This can cause a memory access violation or
>   heap corruption if the DLL and its users use different copies of the
>   CRT libraries.

https://msdn.microsoft.com/en-us/library/ms235460.aspx

I'm using a pre-built SBCL version 1.3.15 x64 on Windows 10. SOIL was
built as a DLL using the Multi-threaded DLL runtime (/MD), as configured in my
libSOIL.dll repo. Without the fix, and error happens on the call to
cffi::foreign-free. With the fix, there is no error as care is taken
to free memory with cl-soil:free-image-data.
```

;; Without fix.
CL-USER> (dirt:load-image-to-c-array "~/Desktop/image.png")
#<C-ARRAY :element-type :UINT8-VEC4 :dimensions (1008 630)>
CL-USER> (cepl:free-c-array *)
; Evaluation aborted on #<SIMPLE-ERROR "An exception occurred in context ~S: ~S. (Exception code: ~S)" {10058E13F3}>.
CL-USER>

;; With fix.
CL-USER> (dirt:load-image-to-c-array "~/Desktop/image.png")
#<C-ARRAY :element-type :UINT8-VEC4 :dimensions (1008 630)>
CL-USER> (cepl:free-c-array *)
NIL
CL-USER>
```

**Comment by cbaggers** [comment]
Oh wow, I totally missed that. Thank-you for persisting and explaining this to me. I'll go and review the other PR and get this in ASAP

**Comment by cbaggers** [comment]
Next week I will run through the CEPL tests so we can get the changes in cl-soil & cepl into the release branches.

Thanks again for the help and patience!

**Pull request merged**
